project_id = "gpuxyahhxwjoovjizbws"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[functions.generate-qr]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.get-ethereum-rpc]
verify_jwt = false

[functions.generate-product-qr]
verify_jwt = false

[functions.view-product]
verify_jwt = false