// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpuxyahhxwjoovjizbws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwdXh5YWhoeHdqb292aml6YndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Njg2NDIsImV4cCI6MjA3MzI0NDY0Mn0.OjgRoXf6LQF5SLgp9JR59-RYlOMfKR4UjOgDwpB7Lsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});